### ISSUE TITLE
RFC 2616 is dead

### ISSUE THREAD

**Issue by JimDabell** [sterchelen/hssp#6]
[RFC2616 is Dead](https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead)

**Comment by afh** [comment]
Seems like [**RFC723** — 6. Response Status Codes](https://datatracker.ietf.org/doc/html/rfc7231#section-6) is a suitable replacement.

**Comment by sterchelen** [comment]
Closed by #10 ; thx @afh

**Comment by afh** [comment]
Thanks for raising awareness about this, @JimDabell 🙏
